# Site settings
title: Congcheng (Gavin)'s World
description: A blog about Congcheng (Gavin) Gong
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://coochg.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Congcheng's World
user_description: My name is Congcheng (Gavin) Gong. 
user_title: Software Developer
email: gong.co@northeastern.edu
twitter_username: coochg
github_username:  coochg
gplus_username:  coochg

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
